services:
  app:
    build:
      context: .
    container_name: ktrend-app-demo
    restart: unless-stopped
    env_file:
      - .env.demo
    environment:
      NEXT_PUBLIC_APP_URL: http://localhost:3000
    command: npm run dev -- --host 0.0.0.0
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
