import {
  type EvidenceRecord,
  type TrendCluster,
  type TrendDailyMetric,
  type TrendMention,
  type TrendSignal
} from "@/types/trend";

const now = "2026-06-24T08:00:00.000Z";

export const seedClusters: TrendCluster[] = [
  {
    id: "11111111-1111-4111-8111-111111111111",
    slug: "glow-cushion",
    primaryTermKo: "글로우 쿠션",
    romanization: "geullou kusyeon",
    zhExplanation: "强调水光底妆和轻薄发光妆感的气垫趋势。",
    enExplanation: "A glow-forward cushion makeup trend focused on dewy skin.",
    usageContext: "常见于美妆测评、妆容教程、通勤轻妆和夏季底妆讨论。",
    tone: "柔和、清透、精致",
    exampleSentenceKo: "요즘은 글로우 쿠션으로 피부 표현을 얇게 하는 게 대세야.",
    exampleSentenceZh: "最近很流行用 glow cushion 做轻薄透亮的底妆。",
    primaryCategory: "beauty",
    secondaryCategories: ["fashion", "photography"],
    relatedProducts: ["气垫底妆", "水光妆滤镜", "肤质增强模板"],
    relatedBrands: ["HERA", "LANEIGE", "Espoir"],
    visualStyleTags: ["dew-skin", "soft-highlight", "glass-look"],
    targetAudience: ["韩国年轻女性", "美妆博主", "通勤妆用户"],
    sourcePlatforms: ["tiktok_creative_center", "google_trends", "manual_research"],
    trendScore: 92,
    growthScore: 88,
    engagementScore: 91,
    freshnessScore: 84,
    authenticityScore: 94,
    productizationScore: 90,
    filterTemplateFitScore: 93,
    viralityScore: 86,
    youngWomenRelevanceScore: 95,
    beautyFeatureFitScore: 96,
    commercialPotentialScore: 93,
    confidenceScore: 91,
    riskLevel: "low",
    riskFlags: [],
    lifecycle: "breakout",
    firstSeenAt: "2026-06-08T00:00:00.000Z",
    lastSeenAt: now,
    collectedSourceCount: 18,
    collectedMentionCount: 94,
    publicSignalCount: 4,
    evidenceCount: 2,
    evidenceCompletenessScore: 86,
    reviewStatus: "approved",
    reviewNotes: "适合延展底妆推荐与肤质模拟功能。"
  },
  {
    id: "22222222-2222-4222-8222-222222222222",
    slug: "insaeng-ne-cut-pose",
    primaryTermKo: "인생네컷 포즈",
    romanization: "insaeng ne keot pojeu",
    zhExplanation: "韩国年轻人在人生四格自拍店流行的拍照姿势合集。",
    enExplanation: "A rising set of poses used in Korean four-cut photo booths.",
    usageContext: "情侣照、闺蜜照、校园打卡和生日纪念拍摄场景。",
    tone: "俏皮、自然、社交属性强",
    exampleSentenceKo: "인생네컷 포즈 추천 영상이 뜨면 바로 저장하게 돼.",
    exampleSentenceZh: "一刷到人生四格姿势推荐视频我就会立刻收藏。",
    primaryCategory: "photography",
    secondaryCategories: ["fashion", "retouching"],
    relatedProducts: ["姿势模板", "拍照引导", "多人构图提示"],
    relatedBrands: ["Photoism", "Life4Cuts"],
    visualStyleTags: ["photo-booth", "youthful", "couple-shot"],
    targetAudience: ["韩国 Z 世代", "情侣", "学生群体"],
    sourcePlatforms: ["tiktok_creative_center", "youtube_charts", "manual_research"],
    trendScore: 95,
    growthScore: 94,
    engagementScore: 89,
    freshnessScore: 87,
    authenticityScore: 96,
    productizationScore: 92,
    filterTemplateFitScore: 90,
    viralityScore: 94,
    youngWomenRelevanceScore: 91,
    beautyFeatureFitScore: 74,
    commercialPotentialScore: 91,
    confidenceScore: 93,
    riskLevel: "low",
    riskFlags: [],
    lifecycle: "breakout",
    firstSeenAt: "2026-06-11T00:00:00.000Z",
    lastSeenAt: now,
    collectedSourceCount: 24,
    collectedMentionCount: 110,
    publicSignalCount: 5,
    evidenceCount: 3,
    evidenceCompletenessScore: 92,
    reviewStatus: "approved",
    reviewNotes: "适合做姿势推荐、构图引导和拍照模板。"
  },
  {
    id: "33333333-3333-4333-8333-333333333333",
    slug: "cool-tone-retouch",
    primaryTermKo: "쿨톤 보정",
    romanization: "kul-ton bojeong",
    zhExplanation: "偏冷色调的人像修图风格，强调通透肤色和蓝灰氛围。",
    enExplanation: "A cool-toned portrait retouch style popular in editing tutorials.",
    usageContext: "自拍修图、证件照调整、情侣照统一色调和滤镜教程。",
    tone: "冷感、精致、氛围感",
    exampleSentenceKo: "쿨톤 보정 템플릿 하나만 있어도 사진 무드가 완전 달라져.",
    exampleSentenceZh: "只要有一个 cool-tone 修图模板，整张照片氛围就完全不同。",
    primaryCategory: "retouching",
    secondaryCategories: ["photography", "beauty"],
    relatedProducts: ["滤镜模板", "肤色校正", "批量色调预设"],
    relatedBrands: ["SNOW", "Foodie", "Lightroom Mobile"],
    visualStyleTags: ["cool-tone", "blue-gray", "airbrushed"],
    targetAudience: ["自拍用户", "修图教程创作者", "女高中生与大学生"],
    sourcePlatforms: ["tiktok_creative_center", "google_trends", "manual_research"],
    trendScore: 90,
    growthScore: 85,
    engagementScore: 84,
    freshnessScore: 82,
    authenticityScore: 89,
    productizationScore: 94,
    filterTemplateFitScore: 97,
    viralityScore: 80,
    youngWomenRelevanceScore: 92,
    beautyFeatureFitScore: 88,
    commercialPotentialScore: 95,
    confidenceScore: 88,
    riskLevel: "low",
    riskFlags: [],
    lifecycle: "steady",
    firstSeenAt: "2026-06-02T00:00:00.000Z",
    lastSeenAt: now,
    collectedSourceCount: 16,
    collectedMentionCount: 80,
    publicSignalCount: 4,
    evidenceCount: 2,
    evidenceCompletenessScore: 79,
    reviewStatus: "approved",
    reviewNotes: "非常适合模板化与一键美化产品能力。"
  },
  {
    id: "44444444-4444-4444-8444-444444444444",
    slug: "ai-id-photo",
    primaryTermKo: "AI 증명사진",
    romanization: "ai jeungmyeong sajin",
    zhExplanation: "使用 AI 自动生成或优化韩式证件照与职业头像的玩法。",
    enExplanation: "AI-generated Korean-style ID photo and profile photo trend.",
    usageContext: "求职照、校园证件照、社媒头像和 AI 写真体验分享。",
    tone: "新鲜、实用、带一点炫技感",
    exampleSentenceKo: "AI 증명사진으로 취업용 프로필을 빨리 맞추는 사람이 많아졌어.",
    exampleSentenceZh: "越来越多人用 AI 证件照快速准备求职头像。",
    primaryCategory: "ai_play",
    secondaryCategories: ["retouching", "photography", "beauty"],
    relatedProducts: ["AI 证件照", "职业头像模板", "背景替换"],
    relatedBrands: ["SNOW", "Studio Labs", "Photoism"],
    visualStyleTags: ["clean-portrait", "professional", "ai-enhanced"],
    targetAudience: ["求职用户", "大学生", "社媒头像用户"],
    sourcePlatforms: ["google_trends", "tiktok_creative_center", "manual_research"],
    trendScore: 97,
    growthScore: 96,
    engagementScore: 90,
    freshnessScore: 95,
    authenticityScore: 88,
    productizationScore: 98,
    filterTemplateFitScore: 94,
    viralityScore: 92,
    youngWomenRelevanceScore: 87,
    beautyFeatureFitScore: 90,
    commercialPotentialScore: 98,
    confidenceScore: 89,
    riskLevel: "medium",
    riskFlags: ["ai-generated", "needs-disclosure"],
    lifecycle: "breakout",
    firstSeenAt: "2026-06-15T00:00:00.000Z",
    lastSeenAt: now,
    collectedSourceCount: 20,
    collectedMentionCount: 124,
    publicSignalCount: 5,
    evidenceCount: 3,
    evidenceCompletenessScore: 89,
    reviewStatus: "approved",
    reviewNotes: "强产品化趋势，适合做 AI 写真与求职照功能。"
  },
  {
    id: "55555555-5555-4555-8555-555555555555",
    slug: "balletcore-commute-look",
    primaryTermKo: "발레코어 출근룩",
    romanization: "ballekheo chulgeun ruk",
    zhExplanation: "把芭蕾风元素穿进韩国日常通勤和约会场景的穿搭趋势。",
    enExplanation: "A balletcore styling wave adapted for Korean commute outfits.",
    usageContext: "通勤穿搭、约会穿搭、轻甜风服装灵感和品牌选品。",
    tone: "柔软、女性化、都市感",
    exampleSentenceKo: "발레코어 출근룩은 리본 디테일이 과하지 않은 게 포인트야.",
    exampleSentenceZh: "韩式 balletcore 通勤穿搭的关键是蝴蝶结元素不要过头。",
    primaryCategory: "fashion",
    secondaryCategories: ["beauty", "photography"],
    relatedProducts: ["穿搭模板", "风格标签", "商品搭配建议"],
    relatedBrands: ["Musinsa", "29CM", "W Concept"],
    visualStyleTags: ["balletcore", "soft-urban", "commute-look"],
    targetAudience: ["韩国年轻女性", "白领", "穿搭博主"],
    sourcePlatforms: ["naver_datalab", "tiktok_creative_center", "manual_research"],
    trendScore: 89,
    growthScore: 86,
    engagementScore: 83,
    freshnessScore: 84,
    authenticityScore: 92,
    productizationScore: 85,
    filterTemplateFitScore: 72,
    viralityScore: 88,
    youngWomenRelevanceScore: 97,
    beautyFeatureFitScore: 68,
    commercialPotentialScore: 90,
    confidenceScore: 90,
    riskLevel: "low",
    riskFlags: [],
    lifecycle: "steady",
    firstSeenAt: "2026-06-01T00:00:00.000Z",
    lastSeenAt: now,
    collectedSourceCount: 15,
    collectedMentionCount: 77,
    publicSignalCount: 3,
    evidenceCount: 2,
    evidenceCompletenessScore: 74,
    reviewStatus: "approved",
    reviewNotes: "适合商品推荐、穿搭灵感和风格识别功能。"
  },
  {
    id: "66666666-6666-4666-8666-666666666666",
    slug: "photo-matjip",
    primaryTermKo: "사진맛집",
    romanization: "sajin matjip",
    zhExplanation: "指非常出片、特别适合拍照打卡的场景或店铺。",
    enExplanation: "A Korean expression for highly photogenic places or setups.",
    usageContext: "咖啡店、展览、快闪店、打卡空间和拍照路线推荐。",
    tone: "分享欲强、轻松、社交友好",
    exampleSentenceKo: "요즘 카페는 커피보다 사진맛집인지 먼저 보게 돼.",
    exampleSentenceZh: "现在大家看咖啡店，往往先看它是不是出片圣地。",
    primaryCategory: "photography",
    secondaryCategories: ["fashion", "beauty"],
    relatedProducts: ["出片地点地图", "场景标签", "打卡攻略模板"],
    relatedBrands: ["Photoism", "Blue Bottle", "Popup Seoul"],
    visualStyleTags: ["photogenic-space", "soft-light", "social-checkin"],
    targetAudience: ["探店用户", "情侣", "内容创作者"],
    sourcePlatforms: ["naver_datalab", "google_trends", "manual_research"],
    trendScore: 87,
    growthScore: 84,
    engagementScore: 82,
    freshnessScore: 80,
    authenticityScore: 95,
    productizationScore: 88,
    filterTemplateFitScore: 78,
    viralityScore: 91,
    youngWomenRelevanceScore: 89,
    beautyFeatureFitScore: 62,
    commercialPotentialScore: 87,
    confidenceScore: 92,
    riskLevel: "low",
    riskFlags: [],
    lifecycle: "steady",
    firstSeenAt: "2026-05-29T00:00:00.000Z",
    lastSeenAt: now,
    collectedSourceCount: 21,
    collectedMentionCount: 90,
    publicSignalCount: 4,
    evidenceCount: 3,
    evidenceCompletenessScore: 88,
    reviewStatus: "approved",
    reviewNotes: "适合内容路线、地点推荐和拍照场景功能。"
  }
];

export const seedMentions: TrendMention[] = [
  {
    id: "aaaa1111-1111-4111-8111-111111111111",
    clusterSlug: "glow-cushion",
    sourcePlatform: "manual_seed",
    sourceUrl: "https://demo.local/source/glow-cushion-youtube-1",
    sourceTitle: "6월 글로우 쿠션 비교",
    sourceAuthorName: "K-Beauty Lab",
    sourceAuthorHandle: "@kbeautylab",
    sourceAuthorRegionSignal: "KR",
    sourceAuthorLanguageSignal: "ko-KR",
    collectedAt: now,
    originalText: "여름엔 글로우 쿠션이 진짜 예쁘게 올라와서 요즘 계속 쓰는 중",
    normalizedText: "여름엔 글로우 쿠션이 진짜 예쁘게 올라와서 요즘 계속 쓰는 중",
    languageRatioKo: 0.97,
    regionConfidence: 0.95,
    localExpressionConfidence: 0.9,
    activityWindowConfidence: 0.88,
    antiRebroadcastConfidence: 0.91,
    authenticityScore: 0.92,
    likesCount: 1430,
    commentsCount: 118,
    viewsCount: 22100,
    sharesCount: 86
  },
  {
    id: "bbbb2222-2222-4222-8222-222222222222",
    clusterSlug: "insaeng-ne-cut-pose",
    sourcePlatform: "manual_seed",
    sourceUrl: "https://demo.local/source/insaeng-ne-cut-1",
    sourceTitle: "인생네컷 포즈 추천",
    sourceAuthorName: "Seoul Snap",
    sourceAuthorHandle: "@seoulsnap",
    sourceAuthorRegionSignal: "KR",
    sourceAuthorLanguageSignal: "ko-KR",
    collectedAt: now,
    originalText: "커플 인생네컷 포즈 저장해두면 실패 확률이 적어",
    normalizedText: "커플 인생네컷 포즈 저장해두면 실패 확률이 적어",
    languageRatioKo: 0.99,
    regionConfidence: 0.97,
    localExpressionConfidence: 0.94,
    activityWindowConfidence: 0.89,
    antiRebroadcastConfidence: 0.95,
    authenticityScore: 0.95,
    likesCount: 2110,
    commentsCount: 154,
    viewsCount: 30100,
    sharesCount: 140
  },
  {
    id: "cccc3333-3333-4333-8333-333333333333",
    clusterSlug: "cool-tone-retouch",
    sourcePlatform: "manual_seed",
    sourceUrl: "https://demo.local/source/cool-tone-retouch-1",
    sourceTitle: "쿨톤 보정 템플릿",
    sourceAuthorName: "Edit Mood",
    sourceAuthorHandle: "@editmood",
    sourceAuthorRegionSignal: "KR",
    sourceAuthorLanguageSignal: "ko-KR",
    collectedAt: now,
    originalText: "쿨톤 보정 프리셋 하나로 인생네컷 분위기까지 맞출 수 있어",
    normalizedText: "쿨톤 보정 프리셋 하나로 인생네컷 분위기까지 맞출 수 있어",
    languageRatioKo: 0.96,
    regionConfidence: 0.9,
    localExpressionConfidence: 0.9,
    activityWindowConfidence: 0.86,
    antiRebroadcastConfidence: 0.89,
    authenticityScore: 0.89,
    likesCount: 1230,
    commentsCount: 66,
    viewsCount: 18200,
    sharesCount: 41
  },
  {
    id: "dddd4444-4444-4444-8444-444444444444",
    clusterSlug: "ai-id-photo",
    sourcePlatform: "manual_seed",
    sourceUrl: "https://demo.local/source/ai-id-photo-1",
    sourceTitle: "AI 증명사진 후기",
    sourceAuthorName: "Creator Mina",
    sourceAuthorHandle: "@minacreates",
    sourceAuthorRegionSignal: "KR",
    sourceAuthorLanguageSignal: "ko-KR",
    collectedAt: now,
    originalText: "취업 준비할 때 AI 증명사진으로 배경이랑 톤 정리하는 사람이 많더라",
    normalizedText: "취업 준비할 때 AI 증명사진으로 배경이랑 톤 정리하는 사람이 많더라",
    languageRatioKo: 0.94,
    regionConfidence: 0.92,
    localExpressionConfidence: 0.86,
    activityWindowConfidence: 0.88,
    antiRebroadcastConfidence: 0.84,
    authenticityScore: 0.89,
    likesCount: 1780,
    commentsCount: 92,
    viewsCount: 28100,
    sharesCount: 111
  },
  {
    id: "eeee5555-5555-4555-8555-555555555555",
    clusterSlug: "balletcore-commute-look",
    sourcePlatform: "manual_seed",
    sourceUrl: "https://demo.local/source/balletcore-commute-1",
    sourceTitle: "발레코어 출근룩 추천",
    sourceAuthorName: "Style Hana",
    sourceAuthorHandle: "@stylehana",
    sourceAuthorRegionSignal: "KR",
    sourceAuthorLanguageSignal: "ko-KR",
    collectedAt: now,
    originalText: "발레코어 출근룩은 리본 한 포인트만 줘도 충분히 분위기가 살아",
    normalizedText: "발레코어 출근룩은 리본 한 포인트만 줘도 충분히 분위기가 살아",
    languageRatioKo: 0.98,
    regionConfidence: 0.93,
    localExpressionConfidence: 0.91,
    activityWindowConfidence: 0.82,
    antiRebroadcastConfidence: 0.92,
    authenticityScore: 0.91,
    likesCount: 980,
    commentsCount: 45,
    viewsCount: 13500,
    sharesCount: 32
  },
  {
    id: "ffff6666-6666-4666-8666-666666666666",
    clusterSlug: "photo-matjip",
    sourcePlatform: "manual_seed",
    sourceUrl: "https://demo.local/source/photo-matjip-1",
    sourceTitle: "서울 사진맛집 카페",
    sourceAuthorName: "Weekend Route",
    sourceAuthorHandle: "@weekendroute",
    sourceAuthorRegionSignal: "KR",
    sourceAuthorLanguageSignal: "ko-KR",
    collectedAt: now,
    originalText: "이 카페는 커피도 괜찮은데 사진맛집이라 주말마다 줄 서",
    normalizedText: "이 카페는 커피도 괜찮은데 사진맛집이라 주말마다 줄 서",
    languageRatioKo: 0.98,
    regionConfidence: 0.96,
    localExpressionConfidence: 0.95,
    activityWindowConfidence: 0.87,
    antiRebroadcastConfidence: 0.9,
    authenticityScore: 0.94,
    likesCount: 1460,
    commentsCount: 73,
    viewsCount: 19000,
    sharesCount: 57
  }
];

export const seedMetrics: TrendDailyMetric[] = [
  { clusterSlug: "glow-cushion", metricDate: "2026-06-20", mentionCount: 12, engagementSum: 12000, trendScore: 84, commercialPotentialScore: 88 },
  { clusterSlug: "glow-cushion", metricDate: "2026-06-21", mentionCount: 15, engagementSum: 13200, trendScore: 87, commercialPotentialScore: 89 },
  { clusterSlug: "glow-cushion", metricDate: "2026-06-22", mentionCount: 19, engagementSum: 14600, trendScore: 90, commercialPotentialScore: 91 },
  { clusterSlug: "glow-cushion", metricDate: "2026-06-23", mentionCount: 21, engagementSum: 15300, trendScore: 92, commercialPotentialScore: 93 },
  { clusterSlug: "glow-cushion", metricDate: "2026-06-24", mentionCount: 27, engagementSum: 16400, trendScore: 94, commercialPotentialScore: 94 },
  { clusterSlug: "insaeng-ne-cut-pose", metricDate: "2026-06-20", mentionCount: 16, engagementSum: 15500, trendScore: 86, commercialPotentialScore: 88 },
  { clusterSlug: "insaeng-ne-cut-pose", metricDate: "2026-06-21", mentionCount: 19, engagementSum: 17100, trendScore: 89, commercialPotentialScore: 89 },
  { clusterSlug: "insaeng-ne-cut-pose", metricDate: "2026-06-22", mentionCount: 22, engagementSum: 18800, trendScore: 92, commercialPotentialScore: 90 },
  { clusterSlug: "insaeng-ne-cut-pose", metricDate: "2026-06-23", mentionCount: 25, engagementSum: 20100, trendScore: 94, commercialPotentialScore: 91 },
  { clusterSlug: "insaeng-ne-cut-pose", metricDate: "2026-06-24", mentionCount: 30, engagementSum: 22600, trendScore: 96, commercialPotentialScore: 92 },
  { clusterSlug: "cool-tone-retouch", metricDate: "2026-06-20", mentionCount: 9, engagementSum: 9100, trendScore: 80, commercialPotentialScore: 90 },
  { clusterSlug: "cool-tone-retouch", metricDate: "2026-06-21", mentionCount: 10, engagementSum: 9800, trendScore: 82, commercialPotentialScore: 91 },
  { clusterSlug: "cool-tone-retouch", metricDate: "2026-06-22", mentionCount: 13, engagementSum: 11000, trendScore: 85, commercialPotentialScore: 93 },
  { clusterSlug: "cool-tone-retouch", metricDate: "2026-06-23", mentionCount: 15, engagementSum: 12100, trendScore: 88, commercialPotentialScore: 94 },
  { clusterSlug: "cool-tone-retouch", metricDate: "2026-06-24", mentionCount: 17, engagementSum: 13100, trendScore: 90, commercialPotentialScore: 95 },
  { clusterSlug: "ai-id-photo", metricDate: "2026-06-20", mentionCount: 8, engagementSum: 10200, trendScore: 84, commercialPotentialScore: 92 },
  { clusterSlug: "ai-id-photo", metricDate: "2026-06-21", mentionCount: 12, engagementSum: 13600, trendScore: 89, commercialPotentialScore: 95 },
  { clusterSlug: "ai-id-photo", metricDate: "2026-06-22", mentionCount: 18, engagementSum: 18200, trendScore: 93, commercialPotentialScore: 96 },
  { clusterSlug: "ai-id-photo", metricDate: "2026-06-23", mentionCount: 22, engagementSum: 21700, trendScore: 96, commercialPotentialScore: 98 },
  { clusterSlug: "ai-id-photo", metricDate: "2026-06-24", mentionCount: 29, engagementSum: 25400, trendScore: 98, commercialPotentialScore: 99 },
  { clusterSlug: "balletcore-commute-look", metricDate: "2026-06-20", mentionCount: 10, engagementSum: 8800, trendScore: 81, commercialPotentialScore: 86 },
  { clusterSlug: "balletcore-commute-look", metricDate: "2026-06-21", mentionCount: 11, engagementSum: 9400, trendScore: 83, commercialPotentialScore: 87 },
  { clusterSlug: "balletcore-commute-look", metricDate: "2026-06-22", mentionCount: 12, engagementSum: 9900, trendScore: 85, commercialPotentialScore: 88 },
  { clusterSlug: "balletcore-commute-look", metricDate: "2026-06-23", mentionCount: 13, engagementSum: 10400, trendScore: 87, commercialPotentialScore: 89 },
  { clusterSlug: "balletcore-commute-look", metricDate: "2026-06-24", mentionCount: 15, engagementSum: 11000, trendScore: 89, commercialPotentialScore: 90 },
  { clusterSlug: "photo-matjip", metricDate: "2026-06-20", mentionCount: 11, engagementSum: 9500, trendScore: 79, commercialPotentialScore: 82 },
  { clusterSlug: "photo-matjip", metricDate: "2026-06-21", mentionCount: 13, engagementSum: 10800, trendScore: 82, commercialPotentialScore: 84 },
  { clusterSlug: "photo-matjip", metricDate: "2026-06-22", mentionCount: 14, engagementSum: 11400, trendScore: 84, commercialPotentialScore: 85 },
  { clusterSlug: "photo-matjip", metricDate: "2026-06-23", mentionCount: 16, engagementSum: 12600, trendScore: 86, commercialPotentialScore: 86 },
  { clusterSlug: "photo-matjip", metricDate: "2026-06-24", mentionCount: 18, engagementSum: 13800, trendScore: 87, commercialPotentialScore: 87 }
];

export const seedSignals: TrendSignal[] = [
  {
    id: "sig-1111",
    clusterSlug: "glow-cushion",
    sourcePlatform: "tiktok_creative_center",
    sourceUrl: "https://ads.tiktok.com/business/creativecenter/",
    signalTitle: "Glow cushion related beauty hashtag momentum",
    signalType: "hashtag_rank",
    regionCode: "KR",
    observedRank: 6,
    observedValue: "7d growth +38%",
    summary: "公开趋势页显示韩系清透底妆相关标签持续上升。",
    confidenceScore: 0.83,
    collectedAt: now
  },
  {
    id: "sig-1112",
    clusterSlug: "glow-cushion",
    sourcePlatform: "google_trends",
    sourceUrl: "https://trends.google.com/trends/",
    signalTitle: "Google Trends KR search surge",
    signalType: "search_surge",
    regionCode: "KR",
    observedValue: "Past 7 days peak",
    summary: "韩国搜索热度在夏季底妆周期内明显抬升。",
    confidenceScore: 0.79,
    collectedAt: now
  },
  {
    id: "sig-2221",
    clusterSlug: "insaeng-ne-cut-pose",
    sourcePlatform: "youtube_charts",
    sourceUrl: "https://charts.youtube.com/",
    signalTitle: "Pose recommendation videos climbing in Shorts discovery",
    signalType: "editorial_pick",
    regionCode: "KR",
    summary: "短视频推荐位中人生四格姿势类视频集中出现。",
    confidenceScore: 0.81,
    collectedAt: now
  },
  {
    id: "sig-2222",
    clusterSlug: "insaeng-ne-cut-pose",
    sourcePlatform: "tiktok_creative_center",
    sourceUrl: "https://ads.tiktok.com/business/creativecenter/",
    signalTitle: "Photo booth pose signal",
    signalType: "hashtag_rank",
    regionCode: "KR",
    observedRank: 4,
    observedValue: "CTR trend up",
    summary: "情侣/闺蜜拍照姿势标签在韩国创意榜中持续靠前。",
    confidenceScore: 0.85,
    collectedAt: now
  },
  {
    id: "sig-3331",
    clusterSlug: "cool-tone-retouch",
    sourcePlatform: "tiktok_creative_center",
    sourceUrl: "https://ads.tiktok.com/business/creativecenter/",
    signalTitle: "Filter template cluster",
    signalType: "keyword_cluster",
    regionCode: "KR",
    observedValue: "Preset/tutorial cluster",
    summary: "公开趋势页里滤镜、色感、模板关键词被反复关联。",
    confidenceScore: 0.74,
    collectedAt: now
  },
  {
    id: "sig-4441",
    clusterSlug: "ai-id-photo",
    sourcePlatform: "google_trends",
    sourceUrl: "https://trends.google.com/trends/",
    signalTitle: "AI profile photo search jump",
    signalType: "search_surge",
    regionCode: "KR",
    observedRank: 3,
    observedValue: "Breakout",
    summary: "AI 证件照/AI 头像相关搜索在韩国短期内爆发。",
    confidenceScore: 0.91,
    collectedAt: now
  },
  {
    id: "sig-5551",
    clusterSlug: "balletcore-commute-look",
    sourcePlatform: "naver_datalab",
    sourceUrl: "https://datalab.naver.com/",
    signalTitle: "Commute look keyword momentum",
    signalType: "search_surge",
    regionCode: "KR",
    observedValue: "20s female trend up",
    summary: "Naver 数据显示通勤穿搭与轻甜风格在年轻女性中同步抬升。",
    confidenceScore: 0.77,
    collectedAt: now
  },
  {
    id: "sig-6661",
    clusterSlug: "photo-matjip",
    sourcePlatform: "naver_datalab",
    sourceUrl: "https://datalab.naver.com/",
    signalTitle: "Photogenic cafe search cluster",
    signalType: "keyword_cluster",
    regionCode: "KR",
    observedValue: "Weekend surge",
    summary: "出片咖啡店和打卡路线关键词在周末周期性升温。",
    confidenceScore: 0.82,
    collectedAt: now
  }
];

export const seedEvidences: EvidenceRecord[] = [
  {
    id: "ev-1111",
    clusterSlug: "glow-cushion",
    sourcePlatform: "manual_research",
    sourceUrl: "https://demo.local/evidence/glow-cushion-1",
    evidenceType: "link",
    headline: "研究员整理的韩妆测评样本",
    excerpt: "来自韩国美妆博主的 3 条公开视频链接均在讨论夏季水光气垫。",
    analystNote: "已人工确认是韩国本土表达，不是中翻韩。",
    submitter: "analyst_li",
    proofStrength: 0.91,
    capturedAt: now,
    status: "verified"
  },
  {
    id: "ev-2221",
    clusterSlug: "insaeng-ne-cut-pose",
    sourcePlatform: "manual_research",
    sourceUrl: "https://demo.local/evidence/insaeng-ne-cut-1",
    evidenceType: "comment_excerpt",
    headline: "评论区反复出现保存/模仿姿势",
    excerpt: "多条韩语评论在请求 pose 模板并分享情侣拍摄结果。",
    analystNote: "适合后续做 pose 模板产品功能。",
    submitter: "analyst_park",
    proofStrength: 0.93,
    capturedAt: now,
    status: "verified"
  },
  {
    id: "ev-3331",
    clusterSlug: "cool-tone-retouch",
    sourcePlatform: "manual_research",
    sourceUrl: "https://demo.local/evidence/cool-tone-retouch-1",
    evidenceType: "screenshot",
    headline: "修图模板界面截图归档",
    excerpt: "研究员保存了两套冷调模板的参数截图与教程片段。",
    analystNote: "证据足够，但来源仍需补更多账号样本。",
    submitter: "analyst_kim",
    proofStrength: 0.74,
    capturedAt: now,
    status: "verified"
  },
  {
    id: "ev-4441",
    clusterSlug: "ai-id-photo",
    sourcePlatform: "manual_research",
    sourceUrl: "https://demo.local/evidence/ai-id-photo-1",
    evidenceType: "analyst_note",
    headline: "AI 证件照使用场景确认",
    excerpt: "求职、校园证件照和社媒头像三类场景都在同步增长。",
    analystNote: "需要品牌安全提醒与 AI disclosure。",
    submitter: "analyst_choi",
    proofStrength: 0.88,
    capturedAt: now,
    status: "verified"
  },
  {
    id: "ev-5551",
    clusterSlug: "balletcore-commute-look",
    sourcePlatform: "manual_research",
    sourceUrl: "https://demo.local/evidence/balletcore-1",
    evidenceType: "link",
    headline: "穿搭灵感链接集",
    excerpt: "研究员收集了 29CM、Musinsa 和博主内容的公开链接。",
    submitter: "analyst_han",
    proofStrength: 0.72,
    capturedAt: now,
    status: "pending"
  },
  {
    id: "ev-6661",
    clusterSlug: "photo-matjip",
    sourcePlatform: "manual_research",
    sourceUrl: "https://demo.local/evidence/photo-matjip-1",
    evidenceType: "link",
    headline: "照片打卡路线证据包",
    excerpt: "含 4 个公开打卡点链接和两条用户评论摘录。",
    analystNote: "证据链较完整，可直接用于详情页说明。",
    submitter: "analyst_yoon",
    proofStrength: 0.9,
    capturedAt: now,
    status: "verified"
  }
];
